# Generated by Django 2.2 on 2020-01-30 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Notes',
        ),
    ]
