# Generated by Django 2.2 on 2020-01-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='very good'),
            preserve_default=False,
        ),
    ]
