# Generated by Django 2.2 on 2020-01-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0005_auto_20200118_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.CharField(max_length=255),
        ),
    ]
